# NOTE: CGO is required for ledger support to work, however goreleaser
# technically doesn't support CGO. Therefore this GoReleaser config is used via
# goreleaser-cross to enable CGO in multiple platforms.
before:
  hooks:
    - go mod tidy
builds:
  - id: darwin-amd64
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
    goos:
      - darwin
    tags:
      - ledger
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"

  # - main: ./cmd/celestia-appd
  #   binary: celestia-appd
  #   env:
  #     - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
  #   goarch:
  #     - amd64
  #     - arm64
  #   goos:
  #     - darwin
  #     - linux
  #   tags:
  #     - ledger
  #   ldflags:
  #     # Ref: https://goreleaser.com/customization/templates/#common-fields
  #     # .Version is the version being released
  #     # .FullCommit is git commit hash goreleaser is using for the release
  #     - -X "{{ .Env.SDKPath }}.Name=celestia-app"
  #     - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
  #     - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
  #     - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
dist: ./build/goreleaser
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of
    # uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
# checksum:
#   name_template: "checksums.txt"
# signs:
#   - artifacts: checksum
#     args:
#       [
#         "--batch",
#         "-u",
#         "{{ .Env.GPG_FINGERPRINT }}",
#         "--output",
#         "${signature}",
#         "--detach-sign",
#         "${artifact}",
#       ]
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
