name: nightly
on:
  workflow_dispatch:
  schedule:
    # runs every day at 6am UTC
    - cron: "0 6 * * *"

env:
  GO_VERSION: '1.21.1'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup kubeconfig
        env:
          KUBECONFIG_FILE: ${{ secrets.KNUU_KUBECONFIG_FILE }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_FILE}" > $HOME/.kube/config

      - name: Run e2e tests
        run: make test-e2e

  race-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests in race mode
        run: make test-race

  fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: jidicula/go-fuzz-action@v1.1.0
        with:
          packages: './...'
          fuzz-time: 2m
          go-version: ${{ env.GO_VERSION }}
